### ISSUE TITLE
Inconsistency between the docs and the example

### ISSUE THREAD

**Issue by ewjoachim** [dropbox/dropbox-sdk-python#12]
The docs says for the class `MetaData` :

```
client_modified – For files, this is the modification time set by the desktop
client when the file was added to Dropbox. Since this time is not verified
(the Dropbox server stores whatever the desktop client sends up), this
should only be used for display purposes (such as sorting) and not, for
example, to determine if a file has changed or not.
```

And [updown.py](https://github.com/dropbox/dropbox-sdk-python/blob/master/example/updown.py#L93) does : 

``` python
if (isinstance(md, dropbox.files.FileMetadata) and
    mtime_dt == md.client_modified and size == md.size):
    print(name, 'is already synced [stats match]')
```

So should we do like the example does or what the doc says ?

**Comment by ewjoachim** [comment]
I don't know if I should open another ticket for this, but there's another really strange thing in the docs : the documentation of FileMetaData says it's "excluding name and path", while it's not. I think what you mean to say is that these elements are not defined in that class but in the Metadata base class. But the effect is the opposite of what you say : FileMetaData does not EXclude these element, it's INcluding them via inheritance.

Note : we're talking about the user documentation. The important thing here is more "what a class has to offer" than "in what class is which attribute declared".

**Comment by braincore** [comment]
Thanks for the report! Using the modification time as `updown.py` does is not ideal for the reason specified in the documentation. We'll add a comment in the example about this. We've been thinking about exposing a file hash to robustly check if a file is already synced, but that would be out-of-scope for now.

We completely agree about the FileMetadata documentation and a fix for it should come out in the next week or two (The issue is present in our other SDKs as well, and we will update them all together).

**Comment by jjssoftware** [comment]
echoed here https://github.com/dropbox/dropbox-sdk-python/issues/55#issuecomment-252472125

**Comment by greg-db** [comment]
Thanks @jjssoftware !

**Comment by rogebrd** [comment]
Both examples and documentation have been updated beyond this point and this is no longer relevant.
