### ISSUE TITLE
how to check the connection to dropbox?

### ISSUE THREAD

**Issue by oohh270** [dropbox/dropbox-sdk-python#122]
Hi,
There is a commend that can check if my connection to dropbox servers is ok?
I want my app to run even if I have no internet connection (right now if I dont have an internet connection I get an exception....)
how can I do it?
Thank you!

**Comment by greg-db** [comment]
You can use any API call to check your connection to the Dropbox API servers. For example, [`users_get_current_account`](https://dropbox-sdk-python.readthedocs.io/en/latest/moduledoc.html#dropbox.dropbox.Dropbox.users_get_current_account) is a good choice since it doesn't have any side effects. If you're offline, it will raise an exception (e.g., `requests.exceptions.ConnectionError`, depending on the particular issue) that you can catch to detect this.
