### ISSUE TITLE
save_body_to_file

### ISSUE THREAD

**Issue by ewjoachim** [dropbox/dropbox-sdk-python#13]
It seems [base.py](https://github.com/dropbox/dropbox-sdk-python/blob/master/dropbox/base.py) expects you to implement a ``_save_body_to_file()`` method, and [dropbox.py](https://github.com/dropbox/dropbox-sdk-python/blob/master/dropbox/dropbox.py) implements a ``save_body_to_file()`` (without the _)

**Comment by ewjoachim** [comment]
Note : the implementation of ``save_body_to_file`` could use a ``try finally`` otherwise you're closing nothing if you make an IOError during the file writing (for example if you write to a file in a nonexisting folder or to a forbidden file). Associated note : the docstring of ``files_download`` states "You must call close on the Response object when you are done with it, otherwise you will max out your available connections.". It would be nice if the underlying object could be used as a context manager. I've looked at request's close method and they say "Note: Should not normally need to be called explicitly." so I don't really know what we're doing there.

**Comment by braincore** [comment]
Thanks for the report! We've fixed the issue in version 3.25 which is available on PyPI.

Also, the docstring for `files_download` has been updated. `close()` is unnecessary if the entire body is read. Since that can't be guaranteed due to unexpected exceptions (as you detail), we recommend using the [`contextlib.closing`](https://docs.python.org/2/library/contextlib.html#contextlib.closing) context manager available in the standard library. The documentation has been updated to reflect this.
