### ISSUE TITLE
Bulk creation of Paper

### ISSUE THREAD

**Issue by foxmask** [dropbox/dropbox-sdk-python#142]
Hi,
Ealier in the issue #87 I asked for the possibility to create paper with an API, now it works perfect, but ... :) 
I try to migrate all my Evernote notes (~2500) with the API and face an issue due to the Ratelimit.

It will be very very helpful to add something in the Dropbox API that allows us to add a bulk of notes that way, as today, the API stucks the creation process when 100 papers have been added.
I dont know if it's possible, maybe by reducing the timeout of the ratelimit or allowing a greater number of creations. Because here the process stucks for 14400 sec for 100 notes. If I launch that 25times, that will take 5days :)
If the API wont provide that possibility ever, any chance to see an import option, for our Evernote.enex files, from the Web Application at least ?
Regards

**Comment by greg-db** [comment]
[Cross-linking for reference: [https://www.dropboxforum.com/t5/API-support/Avoiding-RateLimit/m-p/267005](https://www.dropboxforum.com/t5/API-support/Avoiding-RateLimit/m-p/267005) ]

I can't make any promises, but I'll send this along as a request to increase the limit or offer a bulk import API. (If the team does decide to do either though, it's relatively unlikely it would be done within 5 days anyway.)

Also, since this is about the API and not specific to the SDK, I'll close this in favor of [your forum thread](https://www.dropboxforum.com/t5/API-support/Avoiding-RateLimit/m-p/267005).

Likewise, for any questions or requests for the Paper product itself, please use the [Find answers > Dropbox Paper](https://www.dropboxforum.com/t5/Dropbox-Paper/bd-p/101001008) or [Share an idea > Dropbox Paper](https://www.dropboxforum.com/t5/Dropbox-Paper/idb-p/101002012) forums (or [contact support](https://www.dropbox.com/support)).

**Comment by foxmask** [comment]
thanks
