### ISSUE TITLE
Cancel upload if file exists

### ISSUE THREAD

**Issue by apython1998** [dropbox/dropbox-sdk-python#167]
There is no WriteMode to ignore request if the filename already exists, I think this could be helpful.

**Comment by greg-db** [comment]
If if understand your request correctly, you can get the behavior you're looking for by using `mode=dropbox.files.WriteMode.add` and `autorename=False`, e.g., on [`files_upload`](https://dropbox-sdk-python.readthedocs.io/en/latest/api/dropbox.html#dropbox.dropbox.Dropbox.files_upload). 

That write mode will tell Dropbox not to overwrite an existing file, and that autorename will tell Dropbox to fail the request instead of renaming and committing the file.
