### ISSUE TITLE
Timeout getting shared links

### ISSUE THREAD

**Issue by oji** [dropbox/dropbox-sdk-python#179]
I'm getting read timeout trying to get shared links for a couple of files. 

SDK Version: `9.4.0`
Python Version: `3.6`

```python
# path = https://www.dropbox.com/sh/4qekttnjgywhglq/AADLA1e2YSpG7nF6HDwtA60ua?dl=0
dropbox_connector.sharing_list_shared_links(path=path, direct_only=True)
```

If I disable timeout when instantiating Dropbox, the request succeeds, but it takes 45 seconds to process each file! (there are only two files in that link).

Can you guys look into what can be wrong here?

**Comment by greg-db** [comment]
Thanks for the report! First, to clarify, the `path` value in the comment you shared here is just the shared link to the folder you're referring to, but that's not the actual `path` parameter value you're passing to `sharing_list_shared_links`, correct? (I ask because the `sharing_list_shared_links` method's `path` parameter takes a relative path, not a shared link.)

Anyway, this delay doesn't reproduce for me, so it looks like this may be specific to your account. That being the case, please open an API ticket from the relevant account so we can look into it specifically for you:

[https://www.dropbox.com/developers/contact](https://www.dropbox.com/developers/contact)

Please include the following:

- the `path` value
- the full output you're getting (but redact anything private) including some logging showing how long the call takes

Thanks in advance!
