### ISSUE TITLE
Unhashable type 'Metadata'

### ISSUE THREAD

**Issue by SamSchott** [dropbox/dropbox-sdk-python#182]
It seems like `files.FileMetadata`, `files.FolderMetadata` and `files.DeletedMetadata` are no longer hashable from v9.5. This was never guaranteed by the SDK documentation but some code, including mine, relied on this for example to create sets of Metadata.

Was this an intentional change?

**Comment by greg-db** [comment]
Thanks for the report! I can't say offhand if this was intentional, but I'll raise it with the team. I can't make any promises on getting this changed back though, especially as it wasn't officially documented/supported.

**Comment by SamSchott** [comment]
No worries, obviously there are ways to adapt my code. I was just caught by surprise when bug reports started coming in. So it may be worth highlighting in the release notes.

**Comment by SamSchott** [comment]
No worries, obviously there are ways to adapt my code. I was just caught by surprise when bug reports started coming in. So it may be worth highlighting in the release notes.

**Comment by yuxiang-he** [comment]
Hi just came across this issue. The change was most likely due to https://github.com/dropbox/stone/pull/155/files which allows equality checks on Stone generated classes, but the catch is that stone classes are not hashable as a result. The changes are introduced as a result of the submodule update for Stone in v9.5. The author did not realize the change while writing the docs. We will pay more attention in the coming releases. Does this provide major issues to your code?

**Comment by SamSchott** [comment]
Thanks for the explanation! I've already updated my code to no longer create sets of Metadata objects, so this is no longer an issue for me. I'll close this.
