### ISSUE TITLE
Inconsistent Handling of Upload Paths

### ISSUE THREAD

**Issue by chrisgavinme** [dropbox/dropbox-sdk-python#21]
Behavior when providing upload paths to different methods is inconsistent when an app has permissions restricted to its own folder.

Here is some examples of what I mean

| Method Call | Real Destination | Expected |
| --- | --- | --- |
| `client.put_file("subdir/file.txt", f)` | Dropbox/Apps/MyApp/subdir/file.txt | Yes |
| `client.put_file("MyApp/subdir/file.txt", f)` | Dropbox/Apps/MyApp/MyApp/subdir/file.txt | Yes |
| `client.commit_chunked_upload("subdir/file.txt", id)` | Dropbox/Apps/MyApp/Apps/file.txt | No |
| `client.commit_chunked_upload("MyApp/subdir/file.txt", id)` | Dropbox/Apps/MyApp/subdir/file.txt | No |
| `client.commit_chunked_upload("JustRandomText/subdir/file.txt", id)` | Dropbox/Apps/MyApp/subdir/file.txt | Hell No |

It appears to be related to `put_file` appending `self.session.root` before the path but `commit_chunked_upload` not doing so.

This behavior is inconsistent and confusing. I don't necessarily think the existing code should be changed, since people who have already found and worked around this behavior will have their code broken, but the documentation of `commit_chunked_upload` should make this behavior clear.

**Comment by braincore** [comment]
Thanks for the bug report! This looks to be pretty poor behavior that's been in the v1 SDK for some time. Because it's part of the v1 SDK and is included in the v2 SDK for compatibility reasons, I don't think we'll fix it since we don't want to break existing behavior.

We recommend using the v2 version:
http://dropbox-sdk-python.readthedocs.org/en/master/moduledoc.html#dropbox.base.DropboxBase.files_upload_session_start

Or, if you would like to continue using the v1 SDK, we recommend using the `dropbox.client.ChunkedUploader` helper class which doesn't have the problem you outlined above.
