### ISSUE TITLE
Don't raise an exception on dropbox.files.files_list_folder() call when folder is empty.

### ISSUE THREAD

**Issue by jperras** [dropbox/dropbox-sdk-python#26]
As demonstrated in the current [updown.py](https://github.com/dropbox/dropbox-sdk-python/blob/3c0131946f4c352cce614259e26401722bbfa96f/example/updown.py#L138) example.

The [HTTP-based API docs](https://www.dropbox.com/developers/documentation/http#documentation-files-list_folder) does not make it clear if this is the expected result, either. It seems like the `not_found` error might be what's going on, but if so that seems wrong – we know there's a folder at the specified location, and it just so happens to be empty. Handling this currently entails catching an exception that may or may not be raised depending on the point-in-time number of files in the folder in question.

An empty folder should simply return a [`ListFolderResult`](http://dropbox-sdk-python.readthedocs.org/en/master/moduledoc.html#dropbox.files.ListFolderResult) with no entries.

**Comment by braincore** [comment]
There shouldn't be an error if the folder is empty. As you expect, there should just be no entries. Could you include the error/exception that you're seeing?

**Comment by jperras** [comment]
I believe it was my mistake, actually – in the excitement of porting over parts of our application to the new V2 API things got a little mixed up in our test suite, and I ended up attempting to list the contents of a folder that did not exist.

However, I did notice that this (attempting to fetch the contents of a folder that does not exist) returned an HTTP `409 Conflict`, which seems a somewhat odd choice of status code for the querying of a resource that does not exist.

Relevant portions of the traceback and the log capture for the underlying `urllib3` logger:

```python
Traceback (most recent call last):
  # [snip]
  File "/opt/local/python/virtualenvs/app/local/lib/python2.7/site-packages/dropbox/base.py", line 113, in files_list_folder
    None)
  File "/opt/local/python/virtualenvs/app/local/lib/python2.7/site-packages/dropbox/dropbox.py", line 200, in request
    user_message_locale)
ApiError: ListFolderError(u'path')
---------------------- Captured log -----------------------
# [snip]
dropbox.py                 253 INFO     Request to files/list_folder
connectionpool.py          387 DEBUG    "POST /2/files/list_folder HTTP/1.1" 409 None
```

In a somewhat-related oddity, it also appears as though calling `dropbox.files_list_folder(path='/')` will fail with the same error; it appears that for requests to the root the forward slash must be omitted and an empty string provided instead.

This is somewhat at odds with any non-root request, e.g. `dropbox.files_list_folder(path='/testing.txt')`, which I requires the forward slash to be present; if it is omitted, a `ValidationError` exception is raised:

```python
Traceback (most recent call last):
  File "/vagrant/projects/app/tests/test_dropbox_service.py", line 88, in test_ensure_folders
    service.ensure_folders()
  File "/vagrant/projects/app/application/services.py", line 86, in ensure_folders
    self.client.files_create_folder('testing.txt')
  File "/opt/local/python/virtualenvs/app/local/lib/python2.7/site-packages/dropbox/base.py", line 429, in files_create_folder
    o = files.CreateFolderArg(path)
  File "/opt/local/python/virtualenvs/app/local/lib/python2.7/site-packages/dropbox/files.py", line 3145, in __init__
    self.path = path
  File "/opt/local/python/virtualenvs/app/local/lib/python2.7/site-packages/dropbox/files.py", line 3161, in path
    val = self._path_validator.validate(val)
  File "/opt/local/python/virtualenvs/app/local/lib/python2.7/site-packages/dropbox/babel_validators.py", line 296, in validate
    % (val, self.pattern))
ValidationError: 'For Sale' did not match pattern '/.*'
```

**Comment by cakoose** [comment]
**Why only one HTTP status code?**

Because the HTTP error code isn't always sufficient to determine the exact error, APIs typically include additional information in the response body.  We thought it might be simpler if we used a single HTTP status code (for this class of errors) and have the client always look in the body to see what the exact error is.

(Though we currently only use HTTP 409, we might in the future use HTTP 403 and 404, which is why our SDKs treat all those error codes the same way.  If you're writing your own client from scratch, you should treat 409, 403, 404 the same way and look in the body to see what the actual error is.)

**Why HTTP 409?**

For most HTTP status codes, the HTTP specification mandates specific behaviors.  For example, I initially thought HTTP 412 "precondition failed" might be a good generic error code, but the spec reserves that for specific situations.  Though HTTP 409 is named "conflict", there are actually no rules about how you can use it, allowing us to use it for everything.

We could have invented a new code, as some have done (see: HTTP 420, used by Twitter and the Spring Framework), but were worried about this causing subtle issues for clients.

**Why empty string for the root path?"**

Using "" instead of "/" has advantages when working with paths.  For example, you can always concatenate two paths and get a valid path.  You can also count the number of path components by counting the number of slashes.  These things would require more special case code if the root path were "/".

There are also disadvantages.  For one, most people are used to using "/".  Also, "" is invisible, so programs that show raw paths to users will now have to special-case the root.

**Comment by jperras** [comment]
Thanks for the explanation. While I may disagree with some points on the current usage HTTP status codes, it's nice to see that it was a well considered choice given the constraints you mentioned.

As a general note, this would be excellent information to include in the official documentation, so that others like myself aren't puzzled for too long on this when/if they notice it.

**Comment by braincore** [comment]
Cc-ing @smarx who curates our docs so he sees your note.
