### ISSUE TITLE
Decode csrf_token to be comaptiable with Django session in Python 3

### ISSUE THREAD

**Issue by tksohishi** [dropbox/dropbox-sdk-python#49]
Commented in #47, but the fix in #47 didn't resolve the issue I've got in https://github.com/tksohishi/djdropbox.

**Comment by braincore** [comment]
Thanks for putting up an example. I see what's happening now. Django serializes sessions with JSON (switched from pickle earlier), which means that the CSRF needs to be treated as a string rather than bytes. And regardless of Django's serialization, I'm pretty sure CSRF should be treated as a string.

**Comment by tksohishi** [comment]
@braincore so, are you going to fix it, or should I? :)

**Comment by superzazu** [comment]
I'm having the same problem here. Any idea on when it'll be fixed ? :-)

**Comment by hclarke3** [comment]
Having the same problem as well. Would be happy to submit a PR if it would move the process along.

**Comment by braincore** [comment]
Sorry for the delay. Aiming for an update in the next day.

**Comment by braincore** [comment]
The fix is part of the 5.2.2 release: 28c2588

Thanks again for the `djdropbox` project which made it easy to repro and resolve.

**Comment by tksohishi** [comment]
@braincore :+1:
