### ISSUE TITLE
FolderMetadata.path_display casing issues

### ISSUE THREAD

**Issue by tokeefe** [dropbox/dropbox-sdk-python#63]
1. Create a folder structure in your Dropbox **specifically** as follows `/AAA/BBB/CCC/DDD`
2. Rename folder `CCC` to `CCC_`
3. Rename folder `CCC_` to `ccc`
4. Generate a Dropbox API token and run the following code

```
import dropbox
client = dropbox.Dropbox("ACCESS_TOKEN")
listing =  client.files_list_folder('', recursive=True)
for entry in listing.entries:
        print entry.path_display
```

5. You should see the following output
```
/AAA
/AAA/BBB
/AAA/BBB/ccc
/AAA/BBB/CCC/DDD
```
Issue: You can see that `ccc` suddenly changes back to `CCC`

**Comment by greg-db** [comment]
Thanks for the report @tokeefe ! This is a known issue, due to some technical limitations of how Dropbox works on the backend. For that reason, `path_display` only offers a best effort of displaying the expected casing, but it isn't guaranteed. For that reason, `path_display` is only meant for display purposes, and `path_lower` should be used as the actual source of truth for the location of items.

Anyway, we know that it's not ideal, but if you need the true casing of each component, you can build it from the last path component of each entry, which should have the proper casing, as seen in your example.
